application: codeigniter-appengine
version: 1
runtime: php
api_version: 1
threadsafe: false

handlers:
- url: /user_guide
  static_dir: CodeIgniter_2.1.4/user_guide

- url: /
  script: CodeIgniter_2.1.4/index.php

- url: /(.+)
  script: CodeIgniter_2.1.4/index.php