application: codeigniter-appengine
version: 1
runtime: php
api_version: 1

handlers:
- url: /
  script: CodeIgniter_2.1.4/index.php

- url: /(.+)
  script: CodeIgniter_2.1.4/index.php

- url: CodeIgniter_2.1.4/user_guide
  static_dir: user_guide